### ISSUE TITLE
Reading Error

### ISSUE THREAD

**Issue by nicholasmullikin** [accessibility-oscilloscope/pnt-lut#2]
It seems like there might be a bytes mismatch cause the pnt-lut only shows that's its read after the signal compiler is called twice.

Jan  1 00:08:50 buildroot user.info trigger-data: reading
Jan  1 00:08:50 buildroot user.info trigger-data: (10,)
Jan  1 00:08:51 buildroot user.info trigger-data: reading
Jan  1 00:08:51 buildroot user.info trigger-data: (48,)
Jan  1 00:08:51 buildroot user.info trigger-data: reading
Jan  1 00:08:51 buildroot user.info trigger-data: (10,)
Jan  1 00:08:51 buildroot user.info trigger-data: reading
Jan  1 00:08:51 buildroot user.info sigproc: starting
Jan  1 00:08:51 buildroot user.info sigproc: reading
**Jan  1 00:08:52 buildroot user.info signal-compiler: wrote PGM size 144000**

Jan  1 00:09:36 buildroot user.info trigger-data: (49,)
Jan  1 00:09:36 buildroot user.info trigger-data: writing to oscope
Jan  1 00:09:38 buildroot user.info trigger-data: reading from oscope
Jan  1 00:09:38 buildroot user.info trigger-data: (102, 103, 101, 101, 96, 102, 104, 98, 96, 99, 105, 102, 100, 97, 99, 107, 104, 99, 102, 109, 107, 101, 100, 102, 103, 104, 96, 92, 99, 103, 102, 98, 100, 99, 102, 106, 103, 102, 103, 103, 105, 106, 102, 99, 101, 103, 97,
Jan  1 00:09:38 buildroot user.info trigger-data: wrote 480 bytes
Jan  1 00:09:38 buildroot user.info sigproc: read 480 bytes
Jan  1 00:09:38 buildroot user.info sigproc: writing
Jan  1 00:09:38 buildroot user.info sigproc: wrote 480 bytes
Jan  1 00:09:38 buildroot user.info signal-compiler: read signal 480
Jan  1 00:09:38 buildroot user.info **pnt-lut: read PGM 144015**
Jan  1 00:09:39 buildroot user.info trigger-data: reading
Jan  1 00:09:39 buildroot user.info trigger-data: (10,)
Jan  1 00:09:39 buildroot user.info trigger-data: reading
Jan  1 00:09:39 buildroot user.info trigger-data: (48,)
Jan  1 00:09:40 buildroot user.info trigger-data: reading
Jan  1 00:09:40 buildroot user.info trigger-data: (10,)
Jan  1 00:09:40 buildroot user.info trigger-data: reading
Jan  1 00:09:40 buildroot user.info sigproc: starting
Jan  1 00:09:40 buildroot user.info sigproc: reading
**Jan  1 00:09:41 buildroot user.info signal-compiler: wrote PGM size 144000**

**Comment by cnorthway** [comment]
from this log this looks fine, pnt-lut only reads after the signal compiler read/output the signal image. is there more context i'm missing? otherwise I would think weird behavior came from elsewhere
